### PR TITLE
Add the Support for OpenStack Designate DNS provider

### PR DESCRIPTION
**Pull request by jiangytcn**
Using openstack designate dns provider for private cloud installation.

### CODE REVIEW

**Comment by afritzler** [comment]
Thanks a lot for the PR.

**Comment by jiangytcn** [comment]
thanks @afritzler kubify is quite new to me, and even I create the PR for supporting openstack dns, but I need to commend out route53 setting in dns module,  otherwise the deployment would  be failed. 
this the dns setting in `terraform.tfvar`
```
dns = {
  domain_name = "int.yacloud.io"
  dns_type = "designate"
  hosted_zone_id = "77f75ba6-ada2-4c3e-b0a8-ba9f2e0b61b0"
}
```
Did i miss anything ?

**Comment by afritzler** [comment]
@mandelsoft can you help @jiangytcn out to include another DNS provider type in our module structure?

**Comment by jiangytcn** [comment]
thanks @afritzler  @mandelsoft lemme know if need any further information

**Comment by afritzler** [comment]
Can you please rebase and squash this PR?

**Comment by afritzler** [comment]
Closing due to inactivity. Please feel free to reopen it.

**Pull request closed without merging**
