### PR TITLE
validate terraform is available from PATH

### PR DESCRIPTION
**Pull request by ccwienk**

### CODE REVIEW

**Comment by afritzler** [comment]
Should this be an own command? If so, could you please add it to the command list?

**Comment by afritzler** [comment]
@ccwienk could you please rebase your PR branch?

**Review by afritzler — CHANGES_REQUESTED** [review]

**Comment by afritzler** [comment]
@ccwienk can you have a look at this one?

**Comment by vlerenc** [comment]
@ccwienk Any update? If not, let's close it as it's going stale.

**Pull request closed without merging**
