### PR TITLE
Correct the spelling of Terraform

### PR DESCRIPTION
**Pull request by dcherman**

### CODE REVIEW

**Comment by dcherman** [comment]
I've requested approval to sign the CLA to start contributing to these projects; will post back here if/when I can do so.  Thanks!

**Comment by afritzler** [comment]
@dcherman if you could now sign the CLA we are all set for merging thins PR.

**Comment by afritzler** [comment]
Also, could you please rebase this PR?

**Comment by dcherman** [comment]
@afritzler Sorry for the delay here, I just got approval to sign the CLA and have done so.  Also rebased.

**Pull request merged**
